networks:
    gitea:
        external: false

services:
    server:
        image: docker.gitea.com/gitea:1.23.8
        container_name: gitea
        restart: always
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - GITEA__security__INSTALL_LOCK=true
            - GITEA__database__DB_TYPE=sqlite3
            - GITEA__server__DOMAIN=localhost
            - GITEA__server__ROOT_URL=http://localhost:3000/
        networks:
            - gitea
        volumes:
            - ./gitea:/data
        ports:
            - "3000:3000"
            - "222:22"

    flagd:
        image: ghcr.io/open-feature/flagd:v0.11.5
        command: sleep infinity
        volumes:
            - ./gitea:/repo

volumes:
    gitea:
