networks:
    gitea:
        external: false

services:
    server:
        image: docker.gitea.com/gitea:1.23.8
        container_name: gitea
        restart: always
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - GITEA_DEFAULT__RUN_USER=git
            - GITEA__database__DB_TYPE=sqlite3
            - GITEA__server__ROOT_URL=http://localhost:3000/
            - GITEA__server__START_SSH_SERVER=false
            - GITEA__server__DISABLE_SSH=true
            - GITEA__security__INSTALL_LOCK=true
            - GITEA__repository__ENABLE_PUSH_CREATE_USE=true
            - GITEA__repository__DEFAULT_PUSH_CREATE_PRIVATE=true
            
        networks:
            - gitea
        volumes:
            - gitea-data:/data
            - gitea-config:/etc/gitea
        ports:
            - "3000:3000"
            # - "222:22"

    flagd:
        image: ghcr.io/open-feature/flagd:v0.11.5
        # command: sleep infinity
        volumes:
            - gitea-repo:/repo
        networks:
            - gitea

volumes:
    gitea-data:
    gitea-config:
    gitea-repo:
